backend:
  name: github
  repo: iamguozhen/ganmaJohn
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "portfolio"
    label: "作品集管理"
    files:
      - label: "首頁插畫列表"
        name: "works"
        file: "data.json"
        fields:
          - label: "我的作品清單"
            name: "items"
            widget: "list"
            fields:
              - label: "上傳圖片"
                name: "src"
                widget: "image"
              - label: "作品標題"
                name: "title"
                widget: "string"
              - label: "作品描述"
                name: "desc"
                widget: "text"
