backend:
  name: github
  repo: iamguozhen/ganmaJohn
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "portfolio"
    label: "作品集管理"
    files:
      - label: "首頁插畫列表"
        name: "works"
        file: "data.json"
        fields:
          - label: "我的作品清單"
            name: "items"
            widget: "list"
            fields:
              - label: "作品標題"
                name: "title"
                widget: "string"
              - label: "系列圖片 (第一張將作為封面)"
                name: "image_list"
                widget: "list"
                summary: "{{fields.url}}"
                fields:
                  - {label: "圖片", name: "url", widget: "image"}
              - label: "作品描述"
                name: "desc"
                widget: "text"
                required: false

  - name: "settings"
    label: "網站基本設定"
    files:
      - label: "關於我 & 社群連結"
        name: "site_info"
        file: "settings.json"
        fields:
          - {label: "Instagram 連結", name: "ig_url", widget: "string"}
          - {label: "關於我 - 個人頭像", name: "about_image", widget: "image", required: false}
          - {label: "關於我 - 第一段", name: "about_p1", widget: "text", required: false}
          - {label: "關於我 - 第二段", name: "about_p2", widget: "text", required: false}
